//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        public decimal id { get; set; }
        public decimal reg_inventario_id { get; set; }
        public decimal articulo_id { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> isv { get; set; }
        public decimal cliente_id { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual REGISTRO_INVENTARIO REGISTRO_INVENTARIO { get; set; }
    }
}
