//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENIMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANTENIMIENTO()
        {
            this.REGISTRO_AVERIA = new HashSet<REGISTRO_AVERIA>();
            this.REGISTRO_TECNICOS = new HashSet<REGISTRO_TECNICOS>();
            this.REGISTRO_TAREAS = new HashSet<REGISTRO_TAREAS>();
            this.OBSERVACIONES = new HashSet<OBSERVACIONES>();
            this.REG_MANTENIMIENTO_MQNs = new HashSet<REG_MANTENIMIENTO_MQNs>();
        }
    
        public decimal id { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal cliente_id { get; set; }
        public decimal ciudad_id { get; set; }
    
        public virtual CIUDADES CIUDADES { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_AVERIA> REGISTRO_AVERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TECNICOS> REGISTRO_TECNICOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TAREAS> REGISTRO_TAREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBSERVACIONES> OBSERVACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_MANTENIMIENTO_MQNs> REG_MANTENIMIENTO_MQNs { get; set; }
    }
}
