//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAQUINA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAQUINA()
        {
            this.REG_MANTENIMIENTO_MQNs = new HashSet<REG_MANTENIMIENTO_MQNs>();
            this.REGISTRO_AVERIA = new HashSet<REGISTRO_AVERIA>();
            this.TAREAS = new HashSet<TAREAS>();
            this.OBSERVACIONES = new HashSet<OBSERVACIONES>();
        }
    
        public decimal articulo_id { get; set; }
        public string serialno { get; set; }
        public decimal modelo_id { get; set; }
        public decimal estado_mqn_id { get; set; }
        public decimal cliente_id { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO_MAQUINA ESTADO_MAQUINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_MANTENIMIENTO_MQNs> REG_MANTENIMIENTO_MQNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_AVERIA> REGISTRO_AVERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREAS> TAREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBSERVACIONES> OBSERVACIONES { get; set; }
        public virtual MODELO MODELO { get; set; }
    }
}
