//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InteleSysEntities : DbContext
    {
        public InteleSysEntities()
            : base("name=InteleSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<ARTICULO_INVENTARIO> ARTICULO_INVENTARIO { get; set; }
        public virtual DbSet<AVERIAS> AVERIAS { get; set; }
        public virtual DbSet<CIUDADES> CIUDADES { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<ESTADO_MAQUINA> ESTADO_MAQUINA { get; set; }
        public virtual DbSet<FACTURAS> FACTURAS { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIO { get; set; }
        public virtual DbSet<MANTENIMIENTO> MANTENIMIENTO { get; set; }
        public virtual DbSet<MAQUINA> MAQUINA { get; set; }
        public virtual DbSet<MODELO> MODELO { get; set; }
        public virtual DbSet<OBSERVACIONES> OBSERVACIONES { get; set; }
        public virtual DbSet<PIEZAS> PIEZAS { get; set; }
        public virtual DbSet<REG_MANTENIMIENTO_MQNs> REG_MANTENIMIENTO_MQNs { get; set; }
        public virtual DbSet<REGISTRO_AVERIA> REGISTRO_AVERIA { get; set; }
        public virtual DbSet<REGISTRO_CONSUMO_PIEZAS> REGISTRO_CONSUMO_PIEZAS { get; set; }
        public virtual DbSet<REGISTRO_INVENTARIO> REGISTRO_INVENTARIO { get; set; }
        public virtual DbSet<REGISTRO_TAREAS> REGISTRO_TAREAS { get; set; }
        public virtual DbSet<REGISTRO_TECNICOS> REGISTRO_TECNICOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TAREAS> TAREAS { get; set; }
        public virtual DbSet<TIPO_ARTICULO> TIPO_ARTICULO { get; set; }
        public virtual DbSet<TIPO_TRANSACCION_INVENTARIO> TIPO_TRANSACCION_INVENTARIO { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
