//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIEZAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PIEZAS()
        {
            this.REGISTRO_CONSUMO_PIEZAS = new HashSet<REGISTRO_CONSUMO_PIEZAS>();
        }
    
        public decimal articulo_id { get; set; }
        public string serialno { get; set; }
        public decimal precio_costo { get; set; }
        public Nullable<decimal> isv { get; set; }
        public Nullable<decimal> iva { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> modelo_id { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual MODELO MODELO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_CONSUMO_PIEZAS> REGISTRO_CONSUMO_PIEZAS { get; set; }
    }
}
