//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_MANTENIMIENTO_MQNs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REG_MANTENIMIENTO_MQNs()
        {
            this.REGISTRO_CONSUMO_PIEZAS = new HashSet<REGISTRO_CONSUMO_PIEZAS>();
        }
    
        public decimal mantenimiento_id { get; set; }
        public decimal id { get; set; }
        public decimal maquina_id { get; set; }
    
        public virtual MANTENIMIENTO MANTENIMIENTO { get; set; }
        public virtual MAQUINA MAQUINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_CONSUMO_PIEZAS> REGISTRO_CONSUMO_PIEZAS { get; set; }
    }
}
