//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_CONSUMO_PIEZAS
    {
        public decimal id { get; set; }
        public decimal reg_mantenimiento_mqns_id { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public decimal pieza_id { get; set; }
    
        public virtual PIEZAS PIEZAS { get; set; }
        public virtual REG_MANTENIMIENTO_MQNs REG_MANTENIMIENTO_MQNs { get; set; }
    }
}
