//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_INVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REGISTRO_INVENTARIO()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
        }
    
        public System.DateTime fecha { get; set; }
        public decimal cantidad { get; set; }
        public decimal tipo_trans_inventario_id { get; set; }
        public decimal inventario_id { get; set; }
        public decimal reg_id { get; set; }
        public decimal articulo_id { get; set; }
    
        public virtual ARTICULO_INVENTARIO ARTICULO_INVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
        public virtual TIPO_TRANSACCION_INVENTARIO TIPO_TRANSACCION_INVENTARIO { get; set; }
    }
}
