//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAREAS()
        {
            this.REGISTRO_TAREAS = new HashSet<REGISTRO_TAREAS>();
        }
    
        public decimal id { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_final { get; set; }
        public decimal maquina_id { get; set; }
    
        public virtual MAQUINA MAQUINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TAREAS> REGISTRO_TAREAS { get; set; }
    }
}
