//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.INVENTARIO = new HashSet<INVENTARIO>();
            this.OBSERVACIONES = new HashSet<OBSERVACIONES>();
            this.REGISTRO_AVERIA = new HashSet<REGISTRO_AVERIA>();
            this.REGISTRO_TAREAS = new HashSet<REGISTRO_TAREAS>();
            this.REGISTRO_TECNICOS = new HashSet<REGISTRO_TECNICOS>();
        }
    
        public decimal Id { get; set; }
        public string nombre { get; set; }
        public string contraseña { get; set; }
        public decimal tipo_usuario_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBSERVACIONES> OBSERVACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_AVERIA> REGISTRO_AVERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TAREAS> REGISTRO_TAREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_TECNICOS> REGISTRO_TECNICOS { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
